apiVersion: v1
kind: ConfigMap
metadata:
  name: interop-be-authorization-process-refactor
  namespace: dev-refactor
data:
  EVENTSTORE_DB_USE_SSL: "true"
  EVENTSTORE_DB_SCHEMA: "dev-refactor_authz"
